# Generated by OmopViewer 0.1.0.900
# Be careful editing this file

library(bslib)
library(CodelistGenerator)
library(CohortCharacteristics)
library(DiagrammeR)
library(dplyr)
library(DT)
library(ggplot2)
library(gt)
library(IncidencePrevalence)
library(omopgenerics)
library(OmopSketch)
library(OmopViewer)
library(readr)
library(shiny)
library(shinyWidgets)
library(sortable)
library(visOmopResults)

# preprocess data if it has not been done
fileData <- file.path(getwd(), "data", "shinyData.RData")
if (!file.exists(fileData)) {
  source(file.path(getwd(), "data", "preprocess.R"))
}

# uncomment to load the raw data
# rawData <- OmopViewer::importSummarisedResult(file.path(getwd(), "data"))

# load shiny data
load(fileData)
