# Generated by OmopViewer 0.1.0.900
# Be careful editing this file

server <- function(input, output, session) {
  
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      OmopViewer::exportSummarisedResult(data, fileName = file)
    }
  )
  # fill selectise variables ----
  shiny::observe({
    for (k in seq_along(filterValues)) {
      shinyWidgets::updatePickerInput(
        session,
        inputId = names(filterValues)[k],
        choices = filterValues[[k]],
        selected = filterValues[[k]]
      )
    }
  })
  # summarise_omop_snapshot -----
  ## tidy summarise_omop_snapshot -----
  getTidyDataSummariseOmopSnapshot <- shiny::reactive({
    res <- data |>
      OmopViewer::filterData("summarise_omop_snapshot", input) |>
      OmopViewer::tidyData()

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_omop_snapshot_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_omop_snapshot_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_omop_snapshot_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseOmopSnapshot(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_omop_snapshot_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_omop_snapshot.csv",
    content = function(file) {
      getTidyDataSummariseOmopSnapshot() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_omop_snapshot -----
  ## output 17 -----
  createOutput17 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("summarise_omop_snapshot", input)
    OmopSketch::tableOmopSnapshot(
      result
    )
  })
  output$summarise_omop_snapshot_gt_17 <- gt::render_gt({
    createOutput17()
  })
  output$summarise_omop_snapshot_gt_17_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_omop_snapshot.", input$summarise_omop_snapshot_gt_17_download_type),
    content = function(file) {
      obj <- createOutput17()
      gt::gtsave(data = obj, filename = file)
    }
  )


  # summarise_observation_period -----
  ## tidy summarise_observation_period -----
  getTidyDataSummariseObservationPeriod <- shiny::reactive({
    res <- data |>
      OmopViewer::filterData("summarise_observation_period", input) |>
      OmopViewer::tidyData()

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_observation_period_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_observation_period_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_observation_period_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseObservationPeriod(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_observation_period_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_observation_period.csv",
    content = function(file) {
      getTidyDataSummariseObservationPeriod() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_observation_period -----
  ## output 15 -----
  createOutput15 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("summarise_observation_period", input)
    OmopSketch::tableObservationPeriod(
      result
    )
  })
  output$summarise_observation_period_gt_15 <- gt::render_gt({
    createOutput15()
  })
  output$summarise_observation_period_gt_15_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_observation_period.", input$summarise_observation_period_gt_15_download_type),
    content = function(file) {
      obj <- createOutput15()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 16 -----
  createOutput16 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("summarise_observation_period", input)
    OmopSketch::plotObservationPeriod(
      result,
      variableName = input$summarise_observation_period_ggplot2_16_variableName,
      plotType = input$summarise_observation_period_ggplot2_16_plotType,
      facet = input$summarise_observation_period_ggplot2_16_facet
    )
  })
  output$summarise_observation_period_ggplot2_16 <- shiny::renderPlot({
    createOutput16()
  })
  output$summarise_observation_period_ggplot2_16_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_observation_period.", "png"),
    content = function(file) {
      obj <- createOutput16()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_observation_period_ggplot2_16_download_width),
        height = as.numeric(input$summarise_observation_period_ggplot2_16_download_height),
        units = input$summarise_observation_period_ggplot2_16_download_units,
        dpi = as.numeric(input$summarise_observation_period_ggplot2_16_download_dpi)
      )
    }
  )


  # cohort_code_use -----
  ## tidy cohort_code_use -----
  getTidyDataCohortCodeUse <- shiny::reactive({
    res <- data |>
      OmopViewer::filterData("cohort_code_use", input) |>
      OmopViewer::tidyData()

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$cohort_code_use_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$cohort_code_use_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$cohort_code_use_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataCohortCodeUse(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$cohort_code_use_tidy_download <- shiny::downloadHandler(
    filename = "tidy_cohort_code_use.csv",
    content = function(file) {
      getTidyDataCohortCodeUse() |>
        readr::write_csv(file = file)
    }
  )
  ## output cohort_code_use -----
  ## output 12 -----
  createOutput12 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("cohort_code_use", input)
    CodelistGenerator::tableCohortCodeUse(
      result,
      timing = input$cohort_code_use_gt_12_timing,
      header = input$cohort_code_use_gt_12_header,
      groupColumn = input$cohort_code_use_gt_12_groupColumn,
      hide = input$cohort_code_use_gt_12_hide
    )
  })
  output$cohort_code_use_gt_12 <- gt::render_gt({
    createOutput12()
  })
  output$cohort_code_use_gt_12_download <- shiny::downloadHandler(
    filename = paste0("output_gt_cohort_code_use.", input$cohort_code_use_gt_12_download_type),
    content = function(file) {
      obj <- createOutput12()
      gt::gtsave(data = obj, filename = file)
    }
  )


  # achilles_code_use -----
  ## tidy achilles_code_use -----
  getTidyDataAchillesCodeUse <- shiny::reactive({
    res <- data |>
      OmopViewer::filterData("achilles_code_use", input) |>
      OmopViewer::tidyData()

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$achilles_code_use_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$achilles_code_use_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$achilles_code_use_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataAchillesCodeUse(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$achilles_code_use_tidy_download <- shiny::downloadHandler(
    filename = "tidy_achilles_code_use.csv",
    content = function(file) {
      getTidyDataAchillesCodeUse() |>
        readr::write_csv(file = file)
    }
  )
  ## output achilles_code_use -----
  ## output 14 -----
  createOutput14 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("achilles_code_use", input)
    CodelistGenerator::tableAchillesCodeUse(
      result,
      header = input$achilles_code_use_gt_14_header,
      groupColumn = input$achilles_code_use_gt_14_groupColumn,
      hide = input$achilles_code_use_gt_14_hide
    )
  })
  output$achilles_code_use_gt_14 <- gt::render_gt({
    createOutput14()
  })
  output$achilles_code_use_gt_14_download <- shiny::downloadHandler(
    filename = paste0("output_gt_achilles_code_use.", input$achilles_code_use_gt_14_download_type),
    content = function(file) {
      obj <- createOutput14()
      gt::gtsave(data = obj, filename = file)
    }
  )


  # orphan_code_use -----
  ## tidy orphan_code_use -----
  getTidyDataOrphanCodeUse <- shiny::reactive({
    res <- data |>
      OmopViewer::filterData("orphan_code_use", input) |>
      OmopViewer::tidyData()

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$orphan_code_use_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$orphan_code_use_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$orphan_code_use_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataOrphanCodeUse(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$orphan_code_use_tidy_download <- shiny::downloadHandler(
    filename = "tidy_orphan_code_use.csv",
    content = function(file) {
      getTidyDataOrphanCodeUse() |>
        readr::write_csv(file = file)
    }
  )
  ## output orphan_code_use -----
  ## output 11 -----
  createOutput11 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("orphan_code_use", input)
    CodelistGenerator::tableOrphanCodes(
      result,
      header = input$orphan_code_use_gt_11_header,
      groupColumn = input$orphan_code_use_gt_11_groupColumn,
      hide = input$orphan_code_use_gt_11_hide
    )
  })
  output$orphan_code_use_gt_11 <- gt::render_gt({
    createOutput11()
  })
  output$orphan_code_use_gt_11_download <- shiny::downloadHandler(
    filename = paste0("output_gt_orphan_code_use.", input$orphan_code_use_gt_11_download_type),
    content = function(file) {
      obj <- createOutput11()
      gt::gtsave(data = obj, filename = file)
    }
  )


  # summarise_characteristics -----
  ## tidy summarise_characteristics -----
  getTidyDataSummariseCharacteristics <- shiny::reactive({
    res <- data |>
      OmopViewer::filterData("summarise_characteristics", input) |>
      OmopViewer::tidyData()

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_characteristics_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_characteristics_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_characteristics_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCharacteristics(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_characteristics_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_characteristics.csv",
    content = function(file) {
      getTidyDataSummariseCharacteristics() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_characteristics -----
  ## output 7 -----
  createOutput7 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("summarise_characteristics", input)
    CohortCharacteristics::tableCharacteristics(
      result,
      header = input$summarise_characteristics_gt_7_header,
      groupColumn = input$summarise_characteristics_gt_7_groupColumn,
      hide = input$summarise_characteristics_gt_7_hide
    )
  })
  output$summarise_characteristics_gt_7 <- gt::render_gt({
    createOutput7()
  })
  output$summarise_characteristics_gt_7_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_characteristics.", input$summarise_characteristics_gt_7_download_type),
    content = function(file) {
      obj <- createOutput7()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 8 -----
  createOutput8 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("summarise_characteristics", input)
    CohortCharacteristics::plotCharacteristics(
      result,
      plotType = input$summarise_characteristics_ggplot2_8_plotType,
      facet = input$summarise_characteristics_ggplot2_8_facet,
      colour = input$summarise_characteristics_ggplot2_8_colour
    )
  })
  output$summarise_characteristics_ggplot2_8 <- shiny::renderPlot({
    createOutput8()
  })
  output$summarise_characteristics_ggplot2_8_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_characteristics.", "png"),
    content = function(file) {
      obj <- createOutput8()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_characteristics_ggplot2_8_download_width),
        height = as.numeric(input$summarise_characteristics_ggplot2_8_download_height),
        units = input$summarise_characteristics_ggplot2_8_download_units,
        dpi = as.numeric(input$summarise_characteristics_ggplot2_8_download_dpi)
      )
    }
  )


  # summarise_table -----
  ## tidy summarise_table -----
  getTidyDataSummariseTable <- shiny::reactive({
    res <- data |>
      OmopViewer::filterData("summarise_table", input) |>
      OmopViewer::tidyData()

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_table_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_table_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_table_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseTable(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_table_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_table.csv",
    content = function(file) {
      getTidyDataSummariseTable() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_table -----
  ## output 0 -----
  createOutput0 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("summarise_table", input)
    OmopViewer::omopViewerTable(
      result,
      header = input$summarise_table_gt_0_header,
      group = input$summarise_table_gt_0_group,
      hide = input$summarise_table_gt_0_hide
    )
  })
  output$summarise_table_gt_0 <- gt::render_gt({
    createOutput0()
  })
  output$summarise_table_gt_0_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_table.", input$summarise_table_gt_0_download_type),
    content = function(file) {
      obj <- createOutput0()
      gt::gtsave(data = obj, filename = file)
    }
  )


  # summarise_cohort_attrition -----
  ## tidy summarise_cohort_attrition -----
  getTidyDataSummariseCohortAttrition <- shiny::reactive({
    res <- data |>
      OmopViewer::filterData("summarise_cohort_attrition", input) |>
      OmopViewer::tidyData()

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_cohort_attrition_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_cohort_attrition_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_cohort_attrition_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCohortAttrition(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_cohort_attrition_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_cohort_attrition.csv",
    content = function(file) {
      getTidyDataSummariseCohortAttrition() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_cohort_attrition -----
  ## output 3 -----
  createOutput3 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("summarise_cohort_attrition", input)
    CohortCharacteristics::tableCohortAttrition(
      result,
      header = input$summarise_cohort_attrition_gt_3_header,
      groupColumn = input$summarise_cohort_attrition_gt_3_groupColumn,
      hide = input$summarise_cohort_attrition_gt_3_hide
    )
  })
  output$summarise_cohort_attrition_gt_3 <- gt::render_gt({
    createOutput3()
  })
  output$summarise_cohort_attrition_gt_3_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_cohort_attrition.", input$summarise_cohort_attrition_gt_3_download_type),
    content = function(file) {
      obj <- createOutput3()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 4 -----
  createOutput4 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("summarise_cohort_attrition", input)
    CohortCharacteristics::plotCohortAttrition(
      result
    )
  })
  output$summarise_cohort_attrition_grViz_4 <- DiagrammeR::renderGrViz({
    createOutput4()
  })
  output$summarise_cohort_attrition_grViz_4_download <- shiny::downloadHandler(
    filename = paste0("output_grViz_summarise_cohort_attrition.", "png"),
    content = function(file) {
      obj <- createOutput4()
      DiagrammeR::export_graph(
        graph = obj,
        file_name = file,
        fily_type = "png",
        width = as.numeric(input$summarise_cohort_attrition_grViz_4_download_width),
        height = as.numeric(input$summarise_cohort_attrition_grViz_4_download_height)
      )
    }
  )


  # summarise_cohort_overlap -----
  ## tidy summarise_cohort_overlap -----
  getTidyDataSummariseCohortOverlap <- shiny::reactive({
    res <- data |>
      OmopViewer::filterData("summarise_cohort_overlap", input) |>
      OmopViewer::tidyData()

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_cohort_overlap_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_cohort_overlap_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_cohort_overlap_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCohortOverlap(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_cohort_overlap_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_cohort_overlap.csv",
    content = function(file) {
      getTidyDataSummariseCohortOverlap() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_cohort_overlap -----
  ## output 1 -----
  createOutput1 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("summarise_cohort_overlap", input)
    CohortCharacteristics::tableCohortOverlap(
      result,
      uniqueCombinations = input$summarise_cohort_overlap_gt_1_uniqueCombinations,
      header = input$summarise_cohort_overlap_gt_1_header,
      groupColumn = input$summarise_cohort_overlap_gt_1_groupColumn,
      hide = input$summarise_cohort_overlap_gt_1_hide
    )
  })
  output$summarise_cohort_overlap_gt_1 <- gt::render_gt({
    createOutput1()
  })
  output$summarise_cohort_overlap_gt_1_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_cohort_overlap.", input$summarise_cohort_overlap_gt_1_download_type),
    content = function(file) {
      obj <- createOutput1()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 2 -----
  createOutput2 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("summarise_cohort_overlap", input)
    CohortCharacteristics::plotCohortOverlap(
      result,
      facet = input$summarise_cohort_overlap_ggplot2_2_facet,
      uniqueCombinations = input$summarise_cohort_overlap_ggplot2_2_uniqueCombinations
    ) |> 
      plotly::ggplotly()
  })
  output$summarise_cohort_overlap_ggplot2_2 <- plotly::renderPlotly({
    createOutput2()
  })
  output$summarise_cohort_overlap_ggplot2_2_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_cohort_overlap.", "png"),
    content = function(file) {
      obj <- createOutput2()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_cohort_overlap_ggplot2_2_download_width),
        height = as.numeric(input$summarise_cohort_overlap_ggplot2_2_download_height),
        units = input$summarise_cohort_overlap_ggplot2_2_download_units,
        dpi = as.numeric(input$summarise_cohort_overlap_ggplot2_2_download_dpi)
      )
    }
  )


  # summarise_cohort_timing -----
  ## tidy summarise_cohort_timing -----
  getTidyDataSummariseCohortTiming <- shiny::reactive({
    res <- data |>
      OmopViewer::filterData("summarise_cohort_timing", input) |>
      OmopViewer::tidyData()

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_cohort_timing_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_cohort_timing_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_cohort_timing_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCohortTiming(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_cohort_timing_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_cohort_timing.csv",
    content = function(file) {
      getTidyDataSummariseCohortTiming() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_cohort_timing -----
  ## output 5 -----
  createOutput5 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("summarise_cohort_timing", input)
    CohortCharacteristics::tableCohortTiming(
      result,
      uniqueCombinations = input$summarise_cohort_timing_gt_5_uniqueCombinations,
      timeScale = input$summarise_cohort_timing_gt_5_timeScale,
      header = input$summarise_cohort_timing_gt_5_header,
      groupColumn = input$summarise_cohort_timing_gt_5_groupColumn,
      hide = input$summarise_cohort_timing_gt_5_hide
    )
  })
  output$summarise_cohort_timing_gt_5 <- gt::render_gt({
    createOutput5()
  })
  output$summarise_cohort_timing_gt_5_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_cohort_timing.", input$summarise_cohort_timing_gt_5_download_type),
    content = function(file) {
      obj <- createOutput5()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 6 -----
  createOutput6 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("summarise_cohort_timing", input)
    CohortCharacteristics::plotCohortTiming(
      result,
      plotType = input$summarise_cohort_timing_ggplot2_6_plotType,
      timeScale = input$summarise_cohort_timing_ggplot2_6_timeScale,
      facet = input$summarise_cohort_timing_ggplot2_6_facet,
      colour = input$summarise_cohort_timing_ggplot2_6_colour,
      uniqueCombinations = input$summarise_cohort_timing_ggplot2_6_uniqueCombinations
    )
  })
  output$summarise_cohort_timing_ggplot2_6 <- shiny::renderPlot({
    createOutput6()
  })
  output$summarise_cohort_timing_ggplot2_6_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_cohort_timing.", "png"),
    content = function(file) {
      obj <- createOutput6()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_cohort_timing_ggplot2_6_download_width),
        height = as.numeric(input$summarise_cohort_timing_ggplot2_6_download_height),
        units = input$summarise_cohort_timing_ggplot2_6_download_units,
        dpi = as.numeric(input$summarise_cohort_timing_ggplot2_6_download_dpi)
      )
    }
  )


  # incidence -----
  ## tidy incidence -----
  getTidyDataIncidence <- shiny::reactive({
    res <- data |>
      OmopViewer::filterData("incidence", input) |>
      OmopViewer::tidyData()

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$incidence_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$incidence_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$incidence_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataIncidence(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$incidence_tidy_download <- shiny::downloadHandler(
    filename = "tidy_incidence.csv",
    content = function(file) {
      getTidyDataIncidence() |>
        readr::write_csv(file = file)
    }
  )
  ## output incidence -----
  ## output 18 -----
  createOutput18 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("incidence", input)
    IncidencePrevalence::tableIncidence(
      result,
      header = input$incidence_gt_18_header,
      groupColumn = input$incidence_gt_18_groupColumn,
      hide = input$incidence_gt_18_hide
    )
  })
  output$incidence_gt_18 <- gt::render_gt({
    createOutput18()
  })
  output$incidence_gt_18_download <- shiny::downloadHandler(
    filename = paste0("output_gt_incidence.", input$incidence_gt_18_download_type),
    content = function(file) {
      obj <- createOutput18()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 19 -----
  createOutput19 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("incidence", input)
    IncidencePrevalence::plotIncidence(
      result,
      x = input$incidence_ggplot2_19_x,
      ribbon = input$incidence_ggplot2_19_ribbon,
      facet = input$incidence_ggplot2_19_facet,
      colour = input$incidence_ggplot2_19_colour
    )
  })
  output$incidence_ggplot2_19 <- shiny::renderPlot({
    createOutput19()
  })
  output$incidence_ggplot2_19_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_incidence.", "png"),
    content = function(file) {
      obj <- createOutput19()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$incidence_ggplot2_19_download_width),
        height = as.numeric(input$incidence_ggplot2_19_download_height),
        units = input$incidence_ggplot2_19_download_units,
        dpi = as.numeric(input$incidence_ggplot2_19_download_dpi)
      )
    }
  )


  # incidence_attrition -----
  ## tidy incidence_attrition -----
  getTidyDataIncidenceAttrition <- shiny::reactive({
    res <- data |>
      OmopViewer::filterData("incidence_attrition", input) |>
      OmopViewer::tidyData()

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$incidence_attrition_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$incidence_attrition_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$incidence_attrition_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataIncidenceAttrition(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$incidence_attrition_tidy_download <- shiny::downloadHandler(
    filename = "tidy_incidence_attrition.csv",
    content = function(file) {
      getTidyDataIncidenceAttrition() |>
        readr::write_csv(file = file)
    }
  )
  ## output incidence_attrition -----
  ## output 22 -----
  createOutput22 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("incidence_attrition", input)
    IncidencePrevalence::tableIncidenceAttrition(
      result,
      header = input$incidence_attrition_gt_22_header,
      groupColumn = input$incidence_attrition_gt_22_groupColumn,
      hide = input$incidence_attrition_gt_22_hide
    )
  })
  output$incidence_attrition_gt_22 <- gt::render_gt({
    createOutput22()
  })
  output$incidence_attrition_gt_22_download <- shiny::downloadHandler(
    filename = paste0("output_gt_incidence_attrition.", input$incidence_attrition_gt_22_download_type),
    content = function(file) {
      obj <- createOutput22()
      gt::gtsave(data = obj, filename = file)
    }
  )


  # prevalence -----
  ## tidy prevalence -----
  getTidyDataPrevalence <- shiny::reactive({
    res <- data |>
      OmopViewer::filterData("prevalence", input) |>
      OmopViewer::tidyData()

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$prevalence_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$prevalence_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$prevalence_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataPrevalence(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$prevalence_tidy_download <- shiny::downloadHandler(
    filename = "tidy_prevalence.csv",
    content = function(file) {
      getTidyDataPrevalence() |>
        readr::write_csv(file = file)
    }
  )
  ## output prevalence -----
  ## output 20 -----
  createOutput20 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("prevalence", input)
    IncidencePrevalence::tablePrevalence(
      result,
      header = input$prevalence_gt_20_header,
      groupColumn = input$prevalence_gt_20_groupColumn,
      hide = input$prevalence_gt_20_hide
    )
  })
  output$prevalence_gt_20 <- gt::render_gt({
    createOutput20()
  })
  output$prevalence_gt_20_download <- shiny::downloadHandler(
    filename = paste0("output_gt_prevalence.", input$prevalence_gt_20_download_type),
    content = function(file) {
      obj <- createOutput20()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 21 -----
  createOutput21 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("prevalence", input)
    IncidencePrevalence::plotPrevalence(
      result,
      x = input$prevalence_ggplot2_21_x,
      ribbon = input$prevalence_ggplot2_21_ribbon,
      facet = input$prevalence_ggplot2_21_facet,
      colour = input$prevalence_ggplot2_21_colour
    )
  })
  output$prevalence_ggplot2_21 <- shiny::renderPlot({
    createOutput21()
  })
  output$prevalence_ggplot2_21_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_prevalence.", "png"),
    content = function(file) {
      obj <- createOutput21()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$prevalence_ggplot2_21_download_width),
        height = as.numeric(input$prevalence_ggplot2_21_download_height),
        units = input$prevalence_ggplot2_21_download_units,
        dpi = as.numeric(input$prevalence_ggplot2_21_download_dpi)
      )
    }
  )


  # prevalence_attrition -----
  ## tidy prevalence_attrition -----
  getTidyDataPrevalenceAttrition <- shiny::reactive({
    res <- data |>
      OmopViewer::filterData("prevalence_attrition", input) |>
      OmopViewer::tidyData()

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$prevalence_attrition_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$prevalence_attrition_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$prevalence_attrition_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataPrevalenceAttrition(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$prevalence_attrition_tidy_download <- shiny::downloadHandler(
    filename = "tidy_prevalence_attrition.csv",
    content = function(file) {
      getTidyDataPrevalenceAttrition() |>
        readr::write_csv(file = file)
    }
  )
  ## output prevalence_attrition -----
  ## output 23 -----
  createOutput23 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("prevalence_attrition", input)
    IncidencePrevalence::tablePrevalenceAttrition(
      result,
      header = input$prevalence_attrition_gt_23_header,
      groupColumn = input$prevalence_attrition_gt_23_groupColumn,
      hide = input$prevalence_attrition_gt_23_hide
    )
  })
  output$prevalence_attrition_gt_23 <- gt::render_gt({
    createOutput23()
  })
  output$prevalence_attrition_gt_23_download <- shiny::downloadHandler(
    filename = paste0("output_gt_prevalence_attrition.", input$prevalence_attrition_gt_23_download_type),
    content = function(file) {
      obj <- createOutput23()
      gt::gtsave(data = obj, filename = file)
    }
  )


  # summarise_large_scale_characteristics -----
  ## tidy summarise_large_scale_characteristics -----
  getTidyDataSummariseLargeScaleCharacteristics <- shiny::reactive({
    res <- data |>
      OmopViewer::filterData("summarise_large_scale_characteristics", input) |>
      OmopViewer::tidyData()

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_large_scale_characteristics_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_large_scale_characteristics_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_large_scale_characteristics_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseLargeScaleCharacteristics(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_large_scale_characteristics_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_large_scale_characteristics.csv",
    content = function(file) {
      getTidyDataSummariseLargeScaleCharacteristics() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_large_scale_characteristics -----
  ## output 0 -----
  createOutput0 <- shiny::reactive({
    result <- data |>
      OmopViewer::filterData("summarise_large_scale_characteristics", input)
    OmopViewer::omopViewerTable(
      result,
      header = input$summarise_large_scale_characteristics_gt_0_header,
      group = input$summarise_large_scale_characteristics_gt_0_group,
      hide = input$summarise_large_scale_characteristics_gt_0_hide
    )
  })
  output$summarise_large_scale_characteristics_gt_0 <- gt::render_gt({
    createOutput0()
  })
  output$summarise_large_scale_characteristics_gt_0_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_large_scale_characteristics.", input$summarise_large_scale_characteristics_gt_0_download_type),
    content = function(file) {
      obj <- createOutput0()
      gt::gtsave(data = obj, filename = file)
    }
  )
}
