# Generated by OmopViewer 0.1.0
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      omopgenerics::exportSummarisedResult(data, fileName = file)
    }
  )
  # fill selectise variables ----
  shiny::observe({
    for (k in seq_along(choices)) {
      shiny::updateSelectizeInput(
        session,
        inputId = names(choices)[k],
        choices = choices[[k]],
        selected = selected[[k]],
        server = TRUE
      )

      shinyWidgets::updatePickerInput(session,
                                      inputId = names(choices)[k],
                                      choices = choices[[k]],
                                      selected = selected[[k]])
    }
  })
  
  # summarise_omop_snapshot -----
  ## Table summarise_omop_snapshot ----
  createTableOmopSnapshot <- shiny::reactive({
    if (is.null(dataFiltered$summarise_omop_snapshot)) {
      validate("No snapshot in results")
    }

    OmopSketch::tableOmopSnapshot(
      dataFiltered$summarise_omop_snapshot
    ) %>%
      tab_header(
        title = "Database metadata",
        subtitle = "Overview of data source"
      ) %>%
      tab_options(
        heading.align = "left"
      )
  })
  output$summarise_omop_snapshot_gt <- gt::render_gt({
    createTableOmopSnapshot()
  })
  output$summarise_omop_snapshot_gt_download <- shiny::downloadHandler(
    filename = function() {
      paste0("summarise_omop_snapshot_gt.", input$summarise_omop_snapshot_gt_download_type)
    },
    content = function(file) {
      gt::gtsave(data = createTableOmopSnapshot(), filename = file)
    }
  )

  
  # summarise_observation_period -----
  ## Table summarise_observation_period -----
  createTableObservationPeriod <- shiny::reactive({
    if (is.null(dataFiltered$summarise_observation_period)) {
      validate("No observation period summary in results")
    }
    OmopSketch::tableObservationPeriod(
      dataFiltered$summarise_observation_period
    )%>%
      tab_header(
        title = "Summary of observation periods",
        subtitle = "Observation periods are used to define time under observation for individuals in the data source."
      ) %>%
      tab_options(
        heading.align = "left"
      )
  })
  output$summarise_observation_period_gt <- gt::render_gt({
    createTableObservationPeriod()
  })
  output$summarise_observation_period_gt_download <- shiny::downloadHandler(
    filename = function() {
      paste0("summarise_observation_period_gt.", input$summarise_observation_period_gt_download_type)
    },
    content = function(file) {
      obj <- createTableObservationPeriod()
      gt::gtsave(data = obj, filename = file)
    }
  )
  
  
  # achilles_code_use -----
  ## Table achilles_code_use ----
  createTableAchillesCodeUse <- shiny::reactive({
    if (is.null(dataFiltered$achilles_code_use)) {
      validate("No achilles code use in results")
    }
    achillesFiltered <- dataFiltered$achilles_code_use  |>
      filterData("achilles_code_use", input)

    if (nrow(achillesFiltered) == 0) {
      validate("No results found for selected inputs")
    }

    CodelistGenerator::tableAchillesCodeUse(achillesFiltered,
                                            header = input$achilles_code_use_header,
                                            groupColumn = input$achilles_code_use_groupColumn,
                                            hide = input$achilles_code_use_hide)

  })

  output$achilles_code_use_gt <- gt::render_gt({
    createTableAchillesCodeUse()
  })
 
  output$achilles_code_use_gt_download <- shiny::downloadHandler(
    filename = function() {
      paste0("summarise_achilles_code_use_gt.", input$achilles_code_use_gt_download_type)
    },
    content = function(file) {
      obj <- createTableObservationPeriod()
      gt::gtsave(data = obj, filename = file)
    }
  )
 
  
  # orphan_codes -----
  ## Tidy orphan_codes -----
  getTidyDataOrphanCodes <- shiny::reactive({
    res <- dataFiltered$orphan |>
      filterData("orphan", input) |>
      tidyData()
    
    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$orphan_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]
    
    # pivot
    pivot <- input$orphan_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
                     "estimates" = "estimate_name",
                     "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }
    
    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$orphan_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCharacteristics(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$orphan_tidy_download <- shiny::downloadHandler(
    filename = "tidy_orphan.csv",
    content = function(file) {
      getTidyDataSummariseCharacteristics() |>
        readr::write_csv(file = file)
    }
  )
  ## Table orphan_codes -----
  createTableOrphanCodes <- shiny::reactive({
    
    if (is.null(dataFiltered$prevalence)) {
      validate("No orphan codes in results")
    }
    
    if (is.null(dataFiltered$orphan_code_use)) {
      validate("No orphan codes in results")
    }
    
    result <- dataFiltered$orphan_code_use |>
      dplyr::filter(cdm_name %in% input$orphan_grouping_cdm_name,
                    group_level %in% input$orphan_grouping_codelist_name)
    tbl <- CodelistGenerator::tableOrphanCodes(
      result,
      header = input$orphan_codes_gt_header,
      groupColumn = input$orphan_codes_gt_groupColumn,
      hide = input$orphan_codes_gt_hide
    )
    
    tbl %>%
      tab_header(
        title = "Summary of orphan codes",
        subtitle = "Orphan codes refer to concepts present in the database that are not in a codelist but are related to included codes."
      ) %>%
      tab_options(
        heading.align = "left"
      )
    
  })
  output$orphan_codes_gt <- gt::render_gt({
    createTableOrphanCodes()
  })
  output$orphan_codes_gt_download <- shiny::downloadHandler(
    filename = function() {
      paste0("orphan_codes_gt.", input$orphan_codes_gt_download_type)
    },
    content = function(file) {
      obj <- createTableOrphanCodes()
      gt::gtsave(data = obj, filename = file)
    }
  )
  
  
  # unmapped codes -----
  createOutputUnmapped <- shiny::reactive({
    if (is.null(dataFiltered$unmapped_codes)) {
      validate("No unmapped codes in results")
    }
    
    CodelistGenerator::tableUnmappedCodes(
      dataFiltered$unmapped_codes |>
        dplyr::filter(cdm_name %in% input$unmapped_grouping_cdm_name,
                      group_level %in% input$unmapped_grouping_codelist_name),
      header = input$unmapped_header,
      groupColumn = input$unmapped_groupColumn,
      hide = input$unmapped_hide
    ) %>%
      tab_header(
        title = "Summary of unmapped codes",
        subtitle = "These codes are recorded as source concepts that are mapped to 0"
      ) %>%
      tab_options(
        heading.align = "left"
      )
  })
  output$unmapped_formatted <- gt::render_gt({
    createOutputUnmapped()
  })
  output$unmapped_formatted_download <- shiny::downloadHandler(
    filename = function() {
      paste0("output_gt_orphan.", input$unmapped_formatted_download_type)
    },
    content = function(file) {
      obj <- createOutputUnmapped()
      gt::gtsave(data = obj, filename = file)
    }
  )

  
  # cohort_code_use -----
  ## Tidy cohort_code_use -----
  getTidyDataCohortCodeUse <- shiny::reactive({
    res <- dataFiltered$cohort_code_use |>
      tidyData()
    
    # pivot
    pivot <- input$cohort_code_use_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
                     "estimates" = "estimate_name",
                     "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }
    
    res
  })
  output$cohort_code_use_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataCohortCodeUse(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$cohort_code_use_tidy_download <- shiny::downloadHandler(
    filename = "tidy_cohort_code_use.csv",
    content = function(file) {
      getTidyDataCohortCodeUse() |>
        readr::write_csv(file = file)
    }
  )
  ## Table cohort_code_use -----
  createTableCohortCodeUse <- shiny::reactive({
    if (is.null(dataFiltered$cohort_code_use)) {
      validate("No cohort code use in results")
    }
    result <- dataFiltered$cohort_code_use |>
      filterData("cohort_code_use", input)
    
    if (nrow(result) == 0) {
      validate("No results found for selected inputs")
    }
    
    CodelistGenerator::tableCohortCodeUse(
      result,
      header = input$cohort_code_use_gt_header,
      groupColumn = input$cohort_code_use_gt_groupColumn,
      hide = input$cohort_code_use_gt_hide
    )%>%
      tab_header(
        title = "Summary of cohort code use",
        subtitle = "Codes from codelist observed on day of cohort entry. Note more than one code could be seen for a person on this day (both of which would have led to inclusion)."
      ) %>%
      tab_options(
        heading.align = "left"
      )
  })
  output$cohort_code_use_gt <- gt::render_gt({
    createTableCohortCodeUse()
  })
  output$cohort_code_use_gt_download <- shiny::downloadHandler(
    filename = function() {
      paste0("cohort_code_use_gt.", input$cohort_code_use_gt_download_type)
    },
    content = function(file) {
      obj <- createTableCohortCodeUse()
      gt::gtsave(data = obj, filename = file)
    }
  )

  # summarise_cohort_attrition -----
  ## Table summarise_cohort_attrition ----
  createTableCohortAttrition <- shiny::reactive({
    result <- dataFiltered$summarise_cohort_attrition |>
      filterData("summarise_cohort_attrition", input)

    if (nrow(result) == 0) {
      validate("No results found for selected inputs")
    }

    CohortCharacteristics::tableCohortAttrition(
      result
    )%>%
      tab_header(
        title = "Cohort attrition",
        subtitle = "Attrition of the study cohorts."
      ) %>%
      tab_options(
        heading.align = "left"
      )
  })
  output$summarise_cohort_attrition_gt <- gt::render_gt({
    createTableCohortAttrition()
  })
  output$summarise_cohort_attrition_gt_download <- shiny::downloadHandler(
    filename = function() {
      paste0("summarise_cohort_attrition_gt.", input$summarise_cohort_attrition_gt_download_type)
    },
    content = function(file) {
      obj <- createTableCohortAttrition()
      gt::gtsave(data = obj, filename = file)
    }
  )
  ## Diagram summarise_cohort_attrition -----
  createDiagramCohortAttrition <- shiny::reactive({
    result <- dataFiltered$summarise_cohort_attrition |>
      filterData("summarise_cohort_attrition", input)
    CohortCharacteristics::plotCohortAttrition(
      result
    )
  })
  output$summarise_cohort_attrition_grViz <- DiagrammeR::renderGrViz({
    createDiagramCohortAttrition()
  })
  output$summarise_cohort_attrition_grViz_download <- shiny::downloadHandler(
    filename = "summarise_cohort_attrition_diagram.png",
    content = function(file) {
      createDiagramCohortAttrition() |>
        DiagrammeRsvg::export_svg() |>
        charToRaw() |>
        rsvg::rsvg_png(file,
                 width = input$summarise_cohort_attrition_grViz_download_width,
                 height = input$summarise_cohort_attrition_grViz_download_height)
    }
  )
  
  
  # summarise_characteristics -----
  ## Table summarise_characteristics -----
  createTableSummariseCharacteristics <- shiny::reactive({
    
    if (is.null(dataFiltered$summarise_characteristics)) {
      validate("No summarised characteristics in results")
    }
    
    if(isTRUE(input$summarise_characteristics_include_matched)){
      selectedCohorts <- c(
        input$summarise_characteristics_grouping_cohort_name,
        paste0("matched_to_", input$summarise_characteristics_grouping_cohort_name),
        paste0(input$summarise_characteristics_grouping_cohort_name, "_sampled"),
        paste0(input$summarise_characteristics_grouping_cohort_name, "_matched")
      )
    } else {
      selectedCohorts <- input$summarise_characteristics_grouping_cohort_name
    }
    
    result <- dataFiltered$summarise_characteristics |>
      dplyr::filter(cdm_name %in% input$summarise_characteristics_grouping_cdm_name,
                    group_level %in% selectedCohorts)
    
    if (nrow(result) == 0) {
      validate("No results found for selected inputs")
    }
    CohortCharacteristics::tableCharacteristics(
      result,
      header = input$summarise_characteristics_gt_header,
      groupColumn = input$summarise_characteristics_gt_groupColumn,
      hide = c(input$summarise_characteristics_gt_hide,
               "table_name", "value", "window", "table")
    ) %>%
      tab_header(
        title = "Patient characteristics",
        subtitle = "Summary of patient characteristics relative to cohort entry"
      ) %>%
      tab_options(
        heading.align = "left"
      )
  })
  output$summarise_characteristics_gt <- gt::render_gt({
    createTableSummariseCharacteristics()
  })
  output$summarise_characteristics_gt_download <- shiny::downloadHandler(
    filename = function() {
      paste0("summarise_characteristics_gt.", input$summarise_characteristics_gt_download_type)
    },
    content = function(file) {
      obj <- createTableSummariseCharacteristics()
      gt::gtsave(data = obj, filename = file)
    }
  )
  
  ## Plot age_pyramid ----
  createAgePyramid <- shiny::reactive({
    
    summarise_table <- dataFiltered$summarise_table |>
      filter(cdm_name %in% input$summarise_characteristics_grouping_cdm_name)
    
    if(isTRUE(input$summarise_characteristics_include_matched)){
      summarise_table <- summarise_table |>
        filter(group_level %in%
                 c(
                   input$summarise_characteristics_grouping_cohort_name,
                   paste0("matched_to_", input$summarise_characteristics_grouping_cohort_name),
                   paste0(input$summarise_characteristics_grouping_cohort_name, "_sampled"),
                   paste0(input$summarise_characteristics_grouping_cohort_name, "_matched")
                 )
        )
    } else {
      summarise_table <- summarise_table |>
        filter(group_level %in%
                 input$summarise_characteristics_grouping_cohort_name)
    }
    
    summarise_characteristics <- dataFiltered$summarise_characteristics |>
      filter(cdm_name %in% input$summarise_characteristics_grouping_cdm_name,
             group_level %in% input$summarise_characteristics_grouping_cohort_name)
    
    plotAgeDensity(summarise_table, summarise_characteristics)
    
  })
  
  output$plot_age_pyramid <- shiny::renderPlot({
    createAgePyramid()
  })
  
  output$plot_age_pyramid_download <- shiny::downloadHandler(
    filename = "age_pyramid_plot.png",
    content = function(file) {
      obj <- createAgePyramid()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$plot_age_pyramid_download_width),
        height = as.numeric(input$plot_age_pyramid_download_height),
        units = input$plot_age_pyramid_download_units,
        dpi = as.numeric(input$plot_age_pyramid_download_dpi)
      )
    }
  )
  
  
  
  
  # summarise_large_scale_characteristics -----
  ## Tidy summarise_large_scale_characteristics -----
  getTidyDataSummariseLargeScaleCharacteristics <- shiny::reactive({
    
    if (is.null(dataFiltered$summarise_large_scale_characteristics)) {
      validate("No large scale characteristics in results")
    }
    
    lsc_data <- dataFiltered$summarise_large_scale_characteristics |>
      filter(!is.na(estimate_value)) |>
      filter(estimate_value != "-") |>
      visOmopResults::filterSettings(table_name %in% input$summarise_large_scale_characteristics_grouping_domain,
                                     analysis %in% input$summarise_large_scale_characteristics_settings_analysis) |>
      dplyr::filter(cdm_name %in% input$summarise_large_scale_characteristics_grouping_cdm_name ) |>
      dplyr::filter(group_level  %in% input$summarise_large_scale_characteristics_grouping_cohort_name) |>
      dplyr::filter(variable_level  %in% input$summarise_large_scale_characteristics_grouping_time_window)
    
    if (nrow(lsc_data) == 0) {
      validate("No results found for selected inputs")
    }
    
    tidy(lsc_data) |>
      mutate(concept = paste0(variable_name, " (",
                              concept_id, ")")) |>
      dplyr::select("cdm_name",
                    "concept",
                    "count",
                    "percentage")
    
  })
  output$summarise_large_scale_characteristics_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseLargeScaleCharacteristics() |>
        dplyr::arrange(dplyr::desc(percentage)),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_large_scale_characteristics_tidy_download <- shiny::downloadHandler(
    filename = "summarise_large_scale_characteristics_tidy.csv",
    content = function(file) {
      getTidyDataSummariseLargeScaleCharacteristics() |>
        readr::write_csv(file = file)
    }
  )
  ## Table summarise_large_scale_characteristics -----
  createTableLargeScaleCharacteristics <- shiny::reactive({
    
    if (is.null(dataFiltered$summarise_large_scale_characteristics)) {
      validate("No large scale characteristics in results")
    }
    
    lsc_data <- dataFiltered$summarise_large_scale_characteristics |>
      filter(!is.na(estimate_value)) |>
      filter(estimate_value != "-") |>
      visOmopResults::filterSettings(table_name %in% input$summarise_large_scale_characteristics_grouping_domain,
                                     analysis %in% input$summarise_large_scale_characteristics_settings_analysis) |>
      dplyr::filter(cdm_name %in% input$summarise_large_scale_characteristics_grouping_cdm_name ) |>
      dplyr::filter(group_level  %in% input$summarise_large_scale_characteristics_grouping_cohort_name) |>
      dplyr::filter(variable_level %in% input$summarise_large_scale_characteristics_grouping_time_window)
    
    levels <- lsc_data |>
      dplyr::select("group_level") |>
      dplyr::distinct() |>
      dplyr::pull("group_level")
    
    if(all(sort(gsub(".*_","",levels)) == sort(rep(c("matched","sampled"),floor(length(levels)/2))))){
      lsc_data <- lsc_data |>
        dplyr::filter(grepl("_sampled",group_level)) |>
        dplyr::arrange(group_level,
                       desc(estimate_type),
                       desc(as.numeric(estimate_value))) |>
        rbind(lsc_data |>
                dplyr::filter(grepl("_matched",group_level)) |>
                dplyr::arrange(group_level))
    }else{
      lsc_data <- lsc_data |>
        dplyr::arrange(desc(estimate_type),
                       desc(as.numeric(estimate_value)))
    }
    
    lsc_data |>
      CohortCharacteristics::tableLargeScaleCharacteristics() %>%
      tab_header(
        title = "Large scale characteristics",
        subtitle = "Summary of all records from clinical tables within a time window.
                    The sampled cohort represents individuals from the original cohort, the matched cohort comprises individuals of similar age and sex from the database."
      ) %>%
      tab_options(
        heading.align = "left"
      )
  })
  output$summarise_large_scale_characteristics_gt <- gt::render_gt({
    createTableLargeScaleCharacteristics()
  })
  output$summarise_large_scale_characteristics_gt_download <- shiny::downloadHandler(
    filename = function() {
      paste0("summarise_large_scale_characteristics_gt.", input$summarise_large_scale_characteristics_gt_download_type)
    },
    content = function(file) {
      obj <- createTableLargeScaleCharacteristics()
      gt::gtsave(data = obj, filename = file)
    }
  )
  
  
  
  # compare large_scale_characteristics ----
  filterLargeScaleCharacteristics <- shiny::reactive({
    
    if (is.null(dataFiltered$summarise_large_scale_characteristics)) {
      validate("No large scale characteristics in results")
    }
    dataFiltered$summarise_large_scale_characteristics |>
      filter(variable_level %in% input$compare_large_scale_characteristics_grouping_time_window,
             cdm_name %in% input$compare_large_scale_characteristics_grouping_cdm_name) |>
      filterSettings(table_name %in% input$compare_large_scale_characteristics_grouping_domain,
                     analysis %in% input$compare_large_scale_characteristics_settings_analysis)
    
  })
  ## Tidy large_scale_characteristics ----
  createTidyDataCompareLargeScaleCharacteristics <- shiny::reactive({
    lscFiltered <- filterLargeScaleCharacteristics()
    
    if (nrow(lscFiltered) == 0) {
      validate("No results found for selected inputs")
    }
    
    target_cohort     <- input$compare_large_scale_characteristics_grouping_cohort_1
    comparator_cohort <- input$compare_large_scale_characteristics_grouping_cohort_2
    
    lsc <- lscFiltered |>
      filter(group_level %in% c(target_cohort, comparator_cohort
      )) |>
      filter(estimate_name == "percentage") |>
      omopgenerics::addSettings() |>
      select(database = cdm_name,
             cohort_name = group_level,
             variable_name,
             time_window = variable_level,
             concept_id = additional_level,
             table = table_name,
             percentage = estimate_value) |>
      mutate(percentage = if_else(percentage == "-",
                                  NA, percentage)) |>
      mutate(percentage = as.numeric(percentage)) |>
      pivot_wider(names_from = cohort_name,
                  values_from = percentage)
    
    if(isTRUE(input$compare_large_scale_characteristics_impute_missings)){
      lsc <- lsc |>
        mutate(across(c(target_cohort, comparator_cohort), ~if_else(is.na(.x), 0, .x)))
    }
    
    lsc <- lsc |>
      mutate(across(c(target_cohort, comparator_cohort), ~ as.numeric(.x)/100)) |>
      mutate(smd = (!!sym(target_cohort) - !!sym(comparator_cohort))/sqrt((!!sym(target_cohort)*(1-!!sym(target_cohort)) + !!sym(comparator_cohort)*(1-!!sym(comparator_cohort)))/2)) |>
      arrange(desc(smd))  |>
      mutate(across(c(target_cohort, comparator_cohort), ~ as.numeric(.x)*100)) |>
      mutate(concept = paste0(variable_name, " (",concept_id, ")")) |>
      select("Database" = database,
             "Concept name (concept ID)" = concept,
             "Table" = table,
             "Time window" = time_window,
             target_cohort,
             comparator_cohort,
             "Standardised mean difference" = smd)
    
    return(lsc)
  })
  
  output$compare_large_scale_characteristics_tidy <- DT::renderDT({
    target_cohort     <- input$compare_large_scale_characteristics_grouping_cohort_1
    comparator_cohort <- input$compare_large_scale_characteristics_grouping_cohort_2
    
    round_cols <- c("Standardised mean difference",
                    target_cohort,
                    comparator_cohort)
    
    DT::datatable(createTidyDataCompareLargeScaleCharacteristics(), rownames= FALSE) %>%
      formatRound(columns=c(round_cols), digits=2)
  })
  
  output$compare_large_scale_characteristics_tidy_download <- shiny::downloadHandler(
    filename = "compare_large_scale_characteristics_tidy.csv",
    content = function(file) {
      createTidyDataCompareLargeScaleCharacteristics() |>
        readr::write_csv(file = file)
    }
  )
  
  ## Plot large_scale_characteristics ----
  getPlotlyCompareLsc <- shiny::reactive({
    if (nrow(filterLargeScaleCharacteristics()) == 0) {
      validate("No data to plot")
    }
    
    plotComparedLsc(lsc = filterLargeScaleCharacteristics(),
                    cohorts = c(input$compare_large_scale_characteristics_grouping_cohort_1,
                                input$compare_large_scale_characteristics_grouping_cohort_2),
                    colour = c(input$compare_large_scale_characteristics_colour_1),
                    facet  = c(input$compare_large_scale_characteristics_facet_1),
                    imputeMissings = input$compare_large_scale_characteristics_impute_missings
    )
  })
  
  output$plotly_compare_lsc <- renderPlotly({
    ggplotly(getPlotlyCompareLsc(), tooltip = "Details")
  })
  
  output$plot_compare_large_scale_characteristics_download <- shiny::downloadHandler(
    filename = "output_ggplot2_compare_large_scale_characteristics.png",
    content = function(file) {
      obj <- getPlotlyCompareLsc()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$plot_compare_large_scale_characteristics_download_width),
        height = as.numeric(input$plot_compare_large_scale_characteristics_download_height),
        units = input$plot_compare_large_scale_characteristics_download_units,
        dpi = as.numeric(input$plot_compare_large_scale_characteristics_download_dpi)
      )
    }
  )
  
  
  
  
  
  
  # summarise_cohort_overlap -----
  ## Table cohort_overlap -----
  createTableCohortOverlap <- shiny::reactive({

    if (is.null(dataFiltered$summarise_cohort_overlap)) {
      validate("No cohort overlap in results")
    }

    result <- dataFiltered$summarise_cohort_overlap |>
      filterData("summarise_cohort_overlap", input)

    if (nrow(result) == 0) {
      validate("No results found for selected inputs")
    }

    CohortCharacteristics::tableCohortOverlap(
      result,
      uniqueCombinations = input$summarise_cohort_overlap_gt_uniqueCombinations,
      header = input$summarise_cohort_overlap_gt_header,
      groupColumn = input$summarise_cohort_overlap_gt_groupColumn,
      hide = input$summarise_cohort_overlap_gt_hide
    )%>%
      tab_header(
        title = "Cohort overlap",
        subtitle = "Overlap is where the same individual is in both cohorts. Note their cohort entries do not necessarily overlap."
      ) %>%
      tab_options(
        heading.align = "left"
      )
  })
  output$summarise_cohort_overlap_gt <- gt::render_gt({
    createTableCohortOverlap()
  })
  output$summarise_cohort_overlap_gt_download <- shiny::downloadHandler(
    filename = function(){
      paste0("summarise_cohort_overlap_gt.", input$summarise_cohort_overlap_gt_download_type)
    },
    content = function(file) {
      obj <- createTableCohortOverlap()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## Plot cohort_overlap -----
  createPlotCohortOverlap <- shiny::reactive({
    if (is.null(dataFiltered$summarise_cohort_overlap)) {
      validate("No cohort overlap in results")
    }

    result <- dataFiltered$summarise_cohort_overlap |>
      filterData("summarise_cohort_overlap", input)
    CohortCharacteristics::plotCohortOverlap(
      result,
      facet = input$summarise_cohort_overlap_plot_facet,
      uniqueCombinations = input$summarise_cohort_overlap_plot_uniqueCombinations
    )
  })
  output$summarise_cohort_overlap_plot <- plotly::renderPlotly({
    createPlotCohortOverlap()
  })
  output$summarise_cohort_overlap_plot_download <- shiny::downloadHandler(
    filename = "summarise_cohort_overlap_plot.png",
    content = function(file) {
      obj <- createPlotCohortOverlap()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_cohort_overlap_plot_download_width),
        height = as.numeric(input$summarise_cohort_overlap_plot_download_height),
        units = input$summarise_cohort_overlap_plot_download_units,
        dpi = as.numeric(input$summarise_cohort_overlap_plot_download_dpi)
      )
    }
  )

  
  # summarise_cohort_timing ----
  ## Table cohort_timing -----
  createTableCohortTiming <- shiny::reactive({

    if (is.null(dataFiltered$summarise_cohort_timing)) {
      validate("No cohort timing in results")
    }
    
    result <- dataFiltered$summarise_cohort_timing |>
      filterData("summarise_cohort_timing", input)
    
    if (nrow(result) == 0) {
      validate("No results found for selected inputs")
    }
    
    CohortCharacteristics::tableCohortTiming(
      result,
      timeScale = input$summarise_cohort_timing_gt_time_scale,
      uniqueCombinations = input$summarise_cohort_timing_gt_uniqueCombinations,
    ) %>%
      tab_header(
        title = "Cohort timing",
        subtitle = "Cohort timing refers to the time between an individual entering one cohort and another cohort."
      ) %>%
      tab_options(
        heading.align = "left"
      )
  })
  output$summarise_cohort_timing_gt <- gt::render_gt({
    createTableCohortTiming()
  })
  output$summarise_cohort_timing_gt_download <- shiny::downloadHandler(
    filename = function(){
      paste0("summarise_cohort_timing_gt.", input$summarise_cohort_timing_gt_download_type)
    },
    content = function(file) {
      obj <- createTableCohortTiming()
      gt::gtsave(data = obj, filename = file)
    }
  )
  
  ## Plot cohort_timing -----
  createPlotCohortTiming <- shiny::reactive({
    if (is.null(dataFiltered$summarise_cohort_timing)) {
      validate("No cohort timing in results")
    }
    
    result <- dataFiltered$summarise_cohort_timing |>
      filterData("summarise_cohort_timing", input)
    CohortCharacteristics::plotCohortTiming(
      result,
      facet = input$summarise_cohort_timing_plot_facet,
      uniqueCombinations = input$summarise_cohort_timing_plot_uniqueCombinations
    )
  })
  output$summarise_cohort_timing_plot <- plotly::renderPlotly({
    createPlotCohortTiming()
  })
  output$summarise_cohort_timing_plot_download <- shiny::downloadHandler(
    filename = "summarise_cohort_timing_plot.png",
    content = function(file) {
      obj <- createPlotCohortTiming()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_cohort_timing_plot_download_width),
        height = as.numeric(input$summarise_cohort_timing_plot_download_height),
        units = input$summarise_cohort_timing_plot_download_units,
        dpi = as.numeric(input$summarise_cohort_timing_plot_download_dpi)
      )
    }
  )
  
  
  # incidence -----
  incidenceFiltered <- shiny::reactive({

   dataFiltered$incidence |>
      filter(cdm_name %in%
               input$incidence_grouping_cdm_name) |>
      filterGroup(outcome_cohort_name %in%
                    input$incidence_grouping_outcome_cohort_name) |>
      filterSettings(denominator_age_group %in%
                       input$incidence_settings_denominator_age_group,
                     denominator_sex %in%
                       input$incidence_settings_denominator_sex,
                     denominator_days_prior_observation %in%
                     input$incidence_settings_denominator_days_prior_observation) |>
      filterAdditional(analysis_interval %in%
                         input$incidence_settings_analysis_interval)
  })
  ## Table incidence -----
  createTableIncidence <- shiny::reactive({

    if (is.null(dataFiltered$incidence)) {
      validate("No incidence in results")
    }

    result <- incidenceFiltered()

    if (nrow(result) == 0) {
      validate("No results found for selected inputs")
    }
    IncidencePrevalence::tableIncidence(
      result,
      groupColumn = c("cdm_name", "outcome_cohort_name"),
      hide = "denominator_cohort_name",
      settingsColumn = c("denominator_age_group",
                          "denominator_sex",
                          "denominator_days_prior_observation",
                          "outcome_cohort_name")
    ) %>%
      tab_header(
        title = "Incidence estimates",
        subtitle = "Incidence rates estimated for outcomes of interest"
      ) %>%
      tab_options(
        heading.align = "left"
      )
  })
  output$incidence_gt <- gt::render_gt({
    createTableIncidence()
  })
  output$incidence_gt_download <- shiny::downloadHandler(
    filename = function() {
      paste0("incidence_gt.", input$incidence_gt_download_type)
    },
    content = function(file) {
      obj <- createTableIncidence()
      gt::gtsave(data = obj, filename = file)
    }
  )
  ## Plot incidence_population -----
  createPlotIncidencePopulation <- shiny::reactive({
    plotIncidencePopulation(x = input$incidence_population_plot_x,
                            y =  input$incidence_population_plot_y,
                            result = incidenceFiltered(),
                            facet  = input$incidence_population_plot_facet,
                            colour = input$incidence_population_plot_colour
                            
    )
  })
  
  output$incidence_population_plot <- plotly::renderPlotly({
    plotly::ggplotly(createPlotIncidencePopulation())
  })
  
  output$incidence_population_plot_download <- shiny::downloadHandler(
    filename = "incidence_population_plot.png",
    content = function(file) {
      obj <- createPlotIncidencePopulation()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$incidence_population_plot_download_width),
        height = as.numeric(input$incidence_population_plot_download_height),
        units = input$incidence_population_plot_download_units,
        dpi = as.numeric(input$incidence_population_plot_download_dpi)
      )
    }
  )
  
  ## Plot incidence -----
  createPlotIncidence <- shiny::reactive({
    if (is.null(dataFiltered$incidence)) {
      validate("No incidence in results")
    }

    result <- incidenceFiltered()

    if (nrow(result) == 0) {
      validate("No results found for selected inputs")
    }

    IncidencePrevalence::plotIncidence(
      result,
      x = input$incidence_plot_x,
      ribbon = FALSE,
      facet = input$incidence_plot_facet,
      colour = input$incidence_plot_colour
    )
  })

  output$incidence_plot <- plotly::renderPlotly({
    plotly::ggplotly(createPlotIncidence())
  })
  output$incidence_plot_download <- shiny::downloadHandler(
    filename = "incidence_plot.png",
    content = function(file) {
      obj <- createPlotIncidence()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$incidence_plot_download_width),
        height = as.numeric(input$incidence_plot_download_height),
        units = input$incidence_plot_download_units,
        dpi = as.numeric(input$incidence_plot_download_dpi)
      )
    }
  )

  
  
 
   # prevalence -----
  prevalenceFiltered <- shiny::reactive({

    dataFiltered$prevalence |>
      filter(cdm_name %in%
               input$prevalence_grouping_cdm_name) |>
      filterGroup(outcome_cohort_name %in%
                    input$prevalence_grouping_outcome_cohort_name) |>
      filterSettings(denominator_age_group %in%
                       input$prevalence_settings_denominator_age_group,
                     denominator_sex %in%
                       input$prevalence_settings_denominator_sex,
                     denominator_days_prior_observation %in%
                       input$prevalence_settings_denominator_days_prior_observation) |>
      filterAdditional(analysis_interval %in%
                         input$prevalence_settings_analysis_interval)
  })
  ## Table prevalence ----
  createTablePrevalence <- shiny::reactive({
    if (is.null(dataFiltered$prevalence)) {
      validate("No prevalence in results")
    }

    result <- prevalenceFiltered()

    if (nrow(result) == 0) {
      validate("No results found for selected inputs")
    }

    IncidencePrevalence::tablePrevalence(
      result,
      groupColumn = c("cdm_name", "outcome_cohort_name"),
      hide = "denominator_cohort_name",
      settingsColumn = c("denominator_age_group",
                          "denominator_sex",
                         "denominator_days_prior_observation",
                          "outcome_cohort_name")
    ) %>%
      tab_header(
        title = "Prevalence estimates",
        subtitle = "Prevalence rates estimated for outcomes of interest"
      ) %>%
      tab_options(
        heading.align = "left"
      )
  })
  output$prevalence_gt <- gt::render_gt({
    createTablePrevalence()
  })
  output$prevalence_gt_download <- shiny::downloadHandler(
    filename = function() {
      paste0("prevalence_gt.", input$prevalence_gt_download_type)
    },
    content = function(file) {
      obj <- createTablePrevalence()
      gt::gtsave(data = obj, filename = file)
    }
  )
  ## Plot population_prevalence ----
  createPlotPrevalence <- shiny::reactive({
    
    if (is.null(dataFiltered$prevalence)) {
      validate("No prevalence in results")
    }
    
    result <- prevalenceFiltered()
    
    if (nrow(result) == 0) {
      validate("No results found for selected inputs")
    }
    
    IncidencePrevalence::plotPrevalencePopulation(
      result = result,
      x = input$prevalence_population_plot_x,
      y = input$prevalence_population_plot_y,
      facet = input$prevalence_population_plot_facet,
      colour = input$prevalence_population_plot_colour
    )
  })
  output$prevalence_population_plot <- plotly::renderPlotly({
    plotly::ggplotly(createPlotPrevalence())
  })
  output$prevalence_population_plot_download <- shiny::downloadHandler(
    filename = "prevalence_population_plot.png",
    content = function(file) {
      obj <- createPlotPrevalence()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$prevalence_population_plot_download_width),
        height = as.numeric(input$prevalence_population_plot_download_height),
        units = input$prevalence_population_plot_download_units,
        dpi = as.numeric(input$prevalence_population_plot_download_dpi)
      )
    }
  )
  ## Plot prevalence -----
  createPlotPrevalence <- shiny::reactive({

    if (is.null(dataFiltered$prevalence)) {
      validate("No prevalence in results")
    }

    result <- prevalenceFiltered()

    if (nrow(result) == 0) {
      validate("No results found for selected inputs")
    }

    IncidencePrevalence::plotPrevalence(
      result,
      x = input$prevalence_plot_x,
      ribbon = input$prevalence_plot_ribbon,
      facet = input$prevalence_plot_facet,
      colour = input$prevalence_plot_colour
    )
  })
  output$prevalence_plot <- plotly::renderPlotly({
    plotly::ggplotly(createPlotPrevalence())
  })
  output$prevalence_plot_download <- shiny::downloadHandler(
    filename = "prevalence_plot.png",
    content = function(file) {
      obj <- createPlotPrevalence()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$prevalence_plot_download_width),
        height = as.numeric(input$prevalence_plot_download_height),
        units = input$prevalence_plot_download_units,
        dpi = as.numeric(input$prevalence_plot_download_dpi)
      )
    }
  )
}
