
#' Create a shiny app summarising your phenotyping results
#'
#' @param result A summarised result
#' @param directory Directory where to save report
#'
#' @return A shiny app
#' @export
#'
#' @examples
shinyDiagnostics <- function(result,
                             directory = here::here()){

  rlang::check_installed("omopViewer")

  result |>
    omopViewer::exportStaticApp(
      directory = directory,
      background = c(
        "header" = "phenotypeR diagnostics",
        "body" = "This Shiny App contains results generated by the (phenotypeR)[https://ohdsi.github.io/phenotypeR/] package (version {as.character(utils::packageVersion('CohortCharacteristics'))}) to support the assessment of cohorts in the OMOP CDM." |> glue::glue()
      )
    )
}
